services:
  php:
    build:
      context: ./app/php
      args:
        - PHP_VERSION=${PHP_VERSION}
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - "${LOCAL_WEB_PATH}:/var/www"
      - "${LOCAL_STORAGE_PATH}/app/php/ext:/etc/php/my_ext"
      - "${LOCAL_STORAGE_PATH}/app/php/php.ini:/usr/local/etc/php/php.ini:ro"
      - "${LOCAL_STORAGE_PATH}/app/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro"
      - "${LOCAL_STORAGE_PATH}/app/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "${LOCAL_STORAGE_PATH}/app/php/cron.d/prod_demo:/etc/cron.d/prod_demo:ro"
      - "${LOCAL_STORAGE_PATH}/app/php/supervisor:/etc/supervisor"
      - "${LOCAL_STORAGE_PATH}/app/php/logs:/var/log/php"
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - mysql
      - mongo
    networks:
      my_net_dev:
        ipv4_address: ${IPV4_PREFIX:-"172.28.1."}11
    container_name: ${CONTAINER_PREFIX:-"com_"}php
    dns: 8.8.8.8
    restart: always
  nginx:
    build:
      context: ./app/nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - "${LOCAL_STORAGE_PATH}/app/nginx/conf.d:/etc/nginx/conf.d"
      - "${LOCAL_STORAGE_PATH}/app/nginx/ca:/etc/nginx/ca"
      - "${LOCAL_STORAGE_PATH}/app/nginx/my_modules:/etc/nginx/my_modules"
      - "${LOCAL_STORAGE_PATH}/app/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "${LOCAL_STORAGE_PATH}/app/nginx/mime.types:/etc/nginx/mime.types:ro"
      - "${LOCAL_WEB_PATH}:/var/www"
      - "${LOCAL_STORAGE_PATH}/app/secure:/opt/secure:ro"
      - "${LOCAL_STORAGE_PATH}/app/nginx/logs:/var/log/nginx"
      - "${LOCAL_STORAGE_PATH}/app/nginx/letsencrypt:/etc/letsencrypt"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    networks:
      my_net_dev:
        ipv4_address: ${IPV4_PREFIX:-"172.28.1."}12
    ports:
      - "80:80"
      - "443:443"
      - "8008-8008:8008-8008"
    container_name: ${CONTAINER_PREFIX:-"com_"}nginx
    depends_on:
      - php
    restart: always
  redis:
    image: ${REDIS_VERSION}
    environment:
      - TZ=${TIMEZONE}
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REPLICATION_MODE=master
    volumes:
      - "${LOCAL_STORAGE_PATH}/app/redis/conf.d/redis.conf:/opt/bitnami/redis/etc/redis.conf"
      - "${LOCAL_STORAGE_PATH}/app/redis/db:/bitnami/redis/data"
    networks:
      my_net_dev:
        ipv4_address: ${IPV4_PREFIX:-"172.28.1."}14
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=1024
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    container_name: ${CONTAINER_PREFIX:-"com_"}redis
    restart: always
  mysql:
    image: ${MYSQL_VERSION}
    environment:
      - TZ=${TIMEZONE}
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DEFAULT_BIND_ADDRESS=${IPV4_PREFIX:-"172.28.1."}13
    ports:
      - "3306:3306"
    volumes:
      - "${LOCAL_STORAGE_PATH}/app/mysql/db:/bitnami/mysql/data"
    networks:
      my_net_dev:
        ipv4_address: ${IPV4_PREFIX:-"172.28.1."}13
    container_name: ${CONTAINER_PREFIX:-"com_"}mysql
    restart: always
  mongo:
    image: ${MONGO_VERSION}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
      - MONGODB_ENABLE_IPV6=no
      - MONGODB_ENABLE_DIRECTORY_PER_DB=no
      - MONGODB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - "${LOCAL_STORAGE_PATH}/app/mongo/config/mongodb.conf:/opt/bitnami/mongodb/conf/mongodb.conf"
      - "${LOCAL_STORAGE_PATH}/app/mongo/db:/bitnami"
      - "${LOCAL_STORAGE_PATH}/app/mongo/logs:/opt/bitnami/mongodb/logs"
    networks:
      my_net_dev:
        ipv4_address: ${IPV4_PREFIX:-"172.28.1."}16
    ports:
      - "27017:27017"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    container_name: ${CONTAINER_PREFIX:-"com_"}mongo
    restart: always
  rabbitmq:
    image: ${RABBITMQ_VERSION}
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - TZ=${TIMEZONE}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_ERL_COOKIE=${RABBITMQ_ERL_COOKIE}
      - RABBITMQ_NODE_TYPE=${RABBITMQ_NODE_TYPE}
      - RABBITMQ_NODE_PORT_NUMBER=${RABBITMQ_NODE_PORT_NUMBER}
      - RABBITMQ_CLUSTER_NODE_NAME=${RABBITMQ_CLUSTER_NODE_NAME}
      - RABBITMQ_MANAGER_PORT_NUMBER=${RABBITMQ_MANAGER_PORT_NUMBER}
      - RABBITMQ_MANAGEMENT_BIND_IP=${RABBITMQ_MANAGEMENT_BIND_IP}
      - RABBITMQ_DISK_FREE_LIMIT=${RABBITMQ_DISK_FREE_LIMIT}
      - RABBITMQ_ULIMIT_NOFILES=${RABBITMQ_ULIMIT_NOFILES}
      - RABBITMQ_ENABLE_LDAP=${RABBITMQ_ENABLE_LDAP}
    volumes:
      - "${LOCAL_STORAGE_PATH}/app/rabbitmq/data:/bitnami"
      - "${LOCAL_STORAGE_PATH}/app/rabbitmq/conf.d/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    networks:
      my_net_dev:
        ipv4_address: ${IPV4_PREFIX:-"172.28.1."}20
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: ${CONTAINER_PREFIX:-"com_"}rabbitmq
    restart: always
networks:
  my_net_dev:
    driver: bridge
    external: true