loopback_users = none
cluster_formation.peer_discovery_backend = classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq
deprecated_features.permit.management_metrics_collection = true
