storage:
  dbPath: /data/db
  directoryPerDB: false

systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log
  verbosity: 0

net:
  port: 27017
  bindIpAll: true
  ipv6: false

processManagement:
  fork: false
  pidFilePath: /tmp/mongodb.pid

security:
  authorization: enabled

setParameter:
  enableLocalhostAuthBypass: false
